databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DATABASE_NAME
        fromDatabase:
          name: mysite
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: mysite
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: mysite
          property: password
      - key: DATABASE_PW
        fromDatabase:
          name: mysite
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: mysite
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: mysite
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
